/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mydatabase;

import java.awt.Button;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Hassan
 */
public class MakeOperation extends javax.swing.JFrame {

    /**
     * Creates new form MakeOperation
     */
    String[] elemnts = {"Choose Element", "Table", "Column", "Data", "Primary Key", "Foreign Key"};
    // DefaultComboBoxModel m = new DefaultComboBoxModel<>;

    public MakeOperation(String user, String pass, String dbname) {
        initComponents();
        this.setVisible(true);

    }

    private MakeOperation() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        oprationComboBox1 = new javax.swing.JComboBox<>();
        elemntsComboBox = new javax.swing.JComboBox<>();
        applyButton = new javax.swing.JButton();
        parametersPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        oprationComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Operation...", "Add", "Rename", "Delete", "Modify Data Type" }));
        oprationComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oprationComboBox1ActionPerformed(evt);
            }
        });

        elemntsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Element" }));
        elemntsComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elemntsComboBoxActionPerformed(evt);
            }
        });

        applyButton.setText("+");
        applyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout parametersPanelLayout = new javax.swing.GroupLayout(parametersPanel);
        parametersPanel.setLayout(parametersPanelLayout);
        parametersPanelLayout.setHorizontalGroup(
            parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        parametersPanelLayout.setVerticalGroup(
            parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(applyButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(oprationComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(elemntsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(parametersPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oprationComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(elemntsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(parametersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(applyButton)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    int y = 15;
    private void applyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyButtonActionPerformed
        getParameters(y);
        y += 30;
    }//GEN-LAST:event_applyButtonActionPerformed

    private void oprationComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oprationComboBox1ActionPerformed
        updateElementsComboBox();
    }//GEN-LAST:event_oprationComboBox1ActionPerformed

    private void elemntsComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elemntsComboBoxActionPerformed
        if (elemntsComboBox.getSelectedItem() != null) {
            //getParameters(oprationComboBox1.getSelectedItem().toString(),elemntsComboBox.getSelectedItem().toString());
        }
    }//GEN-LAST:event_elemntsComboBoxActionPerformed
    int i = 1;

    private void getParameters(int y) {

        JLabel t1 = new JLabel("Table " + i + " Name");
        t1.setVisible(true);
        t1.setBounds(0, y, 100, 20);

        JTextField t2 = new JTextField("");
        t2.setVisible(true);
        t2.setBounds(110, y, 200, 20);
        parametersPanel.add(t1);
        parametersPanel.add(t2);
        parametersPanel.revalidate();
        parametersPanel.repaint();
        i++;
    }

    private void updateElementsComboBox() {
        System.out.println("pressed selected opration : " + oprationComboBox1.getSelectedItem().toString());
        if (oprationComboBox1.getSelectedItem().equals("Add")) {
            elemntsComboBox.removeAllItems();
            elemntsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(elemnts));
        } else if (oprationComboBox1.getSelectedItem().toString().equals("Rename")) {
            elemntsComboBox.removeAllItems();
            elemntsComboBox.addItem(elemnts[0]);
            elemntsComboBox.addItem(elemnts[1]);
            elemntsComboBox.addItem(elemnts[2]);
        } else if (oprationComboBox1.getSelectedItem().equals("Delete")) {
            elemntsComboBox.removeAllItems();
            elemntsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(elemnts));
        } else if (oprationComboBox1.getSelectedItem().equals("Add")) {
            elemntsComboBox.addItem(oprationComboBox1.getSelectedItem().toString());
        } else if (oprationComboBox1.getSelectedItem().equals("Modify Data Type")) {
            elemntsComboBox.removeAllItems();
            elemntsComboBox.addItem(elemnts[0]);
            elemntsComboBox.addItem(elemnts[2]);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MakeOperation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MakeOperation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MakeOperation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MakeOperation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MakeOperation().setVisible(true);

            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton applyButton;
    private javax.swing.JComboBox<String> elemntsComboBox;
    private javax.swing.JComboBox<String> oprationComboBox1;
    private javax.swing.JPanel parametersPanel;
    // End of variables declaration//GEN-END:variables
}
